baseurl = "/"
title = "Web Support PayTren"
description = "Web Support Resmi Pendaftaran PayTren"
languageCode = "id"
theme = "paytren"
paginate = "8" # Number of posts per page

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
featured = "featured"
