backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - label: "Judul"
        name: "title"
        widget: "string"

      - label: "Deskripsi"
        name: "descriptoin"
        required: false
        widget: "text"

      - label: "Tanggal Posting"
        name: "date"
        required: false
        widget: "datetime"

      - label: "Kategori"
        name: "categories"
        required: false
        widget: "list"

      - label: "Tag"
        name: "tags"
        required: false
        widget: "list"

      - label: "Penulis"
        name: "authors"
        required: false
        widget: "list"
        
      - label: "Gambar Sampul"
        name: "image"
        required: false
        widget: "image"
        
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:

          - label: Title 
            name: title
            widget: string

          - label: Subtitle
            name: subtitle
            widget: string

          - label: Image
            name: image
            widget: image

          - label: "Blurb"
            name: blurb
            widget: object
            fields: 

             - label: "Heading"
               name: "heading"
               widget: string

             - label: "Text"
               name: "text"
               widget: "text"

          - label: "Intro"
            name: intro
            widget: object
            fields:

              - label: "Heading"
                name: "heading"
                widget: string

              - label: "Text"
                name: "text"
                widget: "text"
         
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:

          - label: Title
            name: title
            widget: string

          - label: Logo
            name: logo
            widget: image

          - label: Body
            name: body
            widget: markdown

          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:

              - label: Heading
                name: heading
                widget: string

              - label: Text
                name: text
                widget: text
